conv = {
    "1Co": "1Co",
    "2Co": "2Co",
    "Ap": "Ap",
    "Cant": "Cc",
    "Ees": "Ees",
    "Eph": "Ef",
    "Eus": "Eus",
    "Ezech": "Ez",
    "Gl": "Gl",
    "Gn": "Gn",
    "Heb": "Hb",
    "Hebrews": "Hb",
    "Is": "Is",
    "Jo": "Jo",
    "John": "Jo",
    "Lc": "Lc",
    "Mat": "Mt",
    "Mt": "Mt",
    "OnePet": "1Pe",
    "Phil": "Fm",
    "Prov": "Pv",
    "Ps": "Ps",
    "Romans": "Rm",
    "job": "Job",
    "Acts": "Act",
    "Baruch": "Ba",
    "Col": "Cl",
    "Coloss": "Cl",
    "Dan": "Dn",
    "Deut": "Dt",
    "Exod": "Ex",
    "Habac": "Hc",
    "Hebr": "Hb",
    "Isaias": "Is",
    "Jer": "Je",
    "Job": "Job",
    "Joel": "Jl",
    "Lam": "Lm",
    "Luke": "Lc",
    "Mark": "Mc",
    "Mc": "Mc",
    "Mc,": "Mc",
    "Num": "Nm",
    "OneThess": "1Ts",
    "Osee": "Os",
    "Rm": "Rm",
    "Rom": "Rm",
    "Wis": "Sa",
    "Zach": "Zc",
    "1John": "1Jo",
    "James": "Tg",
    "At": "Act",
    "Br": "Ba",
    "Cl": "Cl",
    "Ct": "Cc",
    "Dn": "Dn",
    "Dt": "Dt",
    "Ecl": "Eus",
    "Ecle": "Ees",
    "Ef": "Ef",
    "Ez": "Ez",
    "Fl": "Fm",
    "Hab": "Hc",
    "Hb": "Hb",
    "Heb.": "Hb",
    "Jl": "Jl",
    "Jr": "Je",
    "Jó": "Job",
    "Lc.": "Lc",
    "Lm": "Lm",
    "Mq": "Mic",
    "Nm": "Nm",
    "Pr": "Pv",
    "Ps.": "Ps",
    "Sb": "Sa",
    "Sl": "Ps",
    "Tg": "Tg",
    "Zc": "Zc",
    "1 Cor": "1Co",
    "1 Jo": "1Jo",
    "1 Pd": "1Pe",
    "1 Rs": "1Rs",
    "1 Ts": "1Ts",
    "2 Cor": "2Co",
    "2 Pd": "2Pe",
}
